###### By Phaiboon Jaradnaparatana 6434467223

In [1]:
# infomation of stock prices and dividends
# prices and dividends are in the same order from 2566 to 2562 (5 years) respectively
# prices are in different units (THB, USD, etc.) because they are convert to percentage so it doesn't matter
stock_info = {
    "SAPPE": {
        "prices": [86.5, 44.25, 26.25, 19.3, 19.9],
        "dividends": [1.65, 1.1, 1.02, 0.83, 0.66]
    },
    "UNH": {
        "prices": [526.47, 530.18, 502.14, 350.68, 293.98],
        "dividends": [7.29, 6.4, 5.6, 4.83, 4.41]
    },
    "VZ": {
        "prices": [33.6, 40.13, 45.65, 45.65, 43.99],
        "dividends": [2.63, 2.58, 2.54, 2.48, 2.44]
    },
    "ENB": {
        "prices": [33.19, 35.81, 30.59, 23.9, 25],
        "dividends": [3.55, 3.44, 3.34, 3.24, 2.95]
    },
    "PTT": {
        "prices": [35.75, 32.52, 35.13, 37.37, 37.44],
        "dividends": [1.5, 1.96, 0.92, 1.76, 1.7]
    },
    "UL": {
        "prices": [48.48, 49.9, 51.33, 55.55, 50.95],
        "dividends": [1.86, 1.84, 1.83, 1.77, 1.56]
    },
    "KTB": {
        "prices": [18.4, 17.7, 13.2, 11.1, 18.8],
        "dividends": [0.68, 0.42, 0.28, 0.75, 0.72]
    },
    "MSFT": {
        "prices": [340.54, 254.93, 266.72, 198.44, 129.04],
        "dividends": [0.72, 0.65, 0.59, 0.54, 0.85]
    },
    "SAT": {
        "prices": [18.1, 19.9, 19.19, 14.03, 12.27],
        "dividends": [1.5, 1.42, 0.53, 1.15, 1.06]
    },
    "TSMC": {
        "prices": [104.0, 74.19, 117.85, 105.49, 55.06],
        "dividends": [1.45, 1.43, 1.48, 1.35, 1.61]
    },
    "SCB": {
        "prices": [105.06, 110.92, 109.27, 75.96, 127.75],
        "dividends": [10.34, 6.69, 4.13, 3.73, 6.25]
    },
    "JPM": {
        "prices": [139.22, 119.88, 141.83, 94.14, 97.41],
        "dividends": [4.1, 4.0, 3.8, 3.6, 3.4]
    },
    "Visa": {
        "prices": [232.43, 203.36, 216.84, 118.15, 160.96],
        "dividends": [1.8, 1.5, 1.28, 1.2, 1.0]
    },
    "META": {
        "prices": [249.37, 193.06, 319.35, 231.42, 178.55],
        "dividends": [0, 0, 0, 0, 0]
    },
    "TOP": {
        "prices": [53.75, 56.25, 49.5, 52.0, 69.75],
        "dividends": [2.35, 4.0, 1.3, 0.5, 2.15]
    },
    "BMWG": {
        "prices": [100.78, 83.38, 88.49, 72.23, 73.14],
        "dividends": [8.5, 5.8, 1.9, 2.5, 3.5]
    },
    "AP": {
        "prices": [11.3, 11.6, 9.55, 7.25, 7.45],
        "dividends": [0.7, 0.65, 0.5, 0.45, 0.4]
    },
    "ABBV": {
        "prices": [154.97, 161.61, 135.4, 107.15, 88.54],
        "dividends": [5.92, 5.64, 5.2, 4.72, 4.28]
    },
    "KBS": {
        "prices": [5.5, 4.6, 3.52, 2.68, 3.21],
        "dividends": [0.5, 0, 0, 0.06, 0.12]
    },
    "NVDA": {
        "prices": [19.53, 24.45, 12.96, 5.89, 3.57],
        "dividends": [0.16, 0.16, 0.4, 0.64, 0.64]
    },
    "Cpaxt": {
        "prices": [27.0, 0.0, 0.0, 0.0, 0.0],
        "dividends": [0.0, 0.0, 0.0, 0.0, 0.0]
    },
    "APPLE": {
        "prices": [161.89, 154.42, 149.17, 95.97, 54.5],
        "dividends": [0.24, 0.23, 0.22, 0.66, 0.76]
    },
    "AVGO": {
        "prices": [111.63, 55.91, 66.54, 43.79, 31.6],
        "dividends": [19.05, 16.9, 14.9, 13.35, 11.2]
    },
    "LH": {
        "prices": [8.15, 9.9, 8.8, 7.95, 9.8],
        "dividends": [0.55, 0.5, 0.55, 0.6, 0.65]
    },
    "SIRI": {
        "prices": [1.77, 1.76, 1.23, 0.81, 1.09],
        "dividends": [0.2, 0.15, 0.06, 0.04, 0.08]
    },
    "CVX": {
        "prices": [144.46, 167.26, 105.55, 72.18, 97.47],
        "dividends": [6.04, 5.68, 5.31, 5.16, 4.76]
    },
    "ORI": {
        "prices": [8.45, 12.1, 10.7, 6.68, 5.56],
        "dividends": [0.73, 0.57, 0.61, 0.29, 0.565]
    },
    "PSEC": {
        "prices": [5.99, 6.99, 8.41, 5.41, 6.44],
        "dividends": [0.72, 0.72, 0.72, 0.72, 0.72]
    },
    "KCE": {
        "prices": [46.99, 86.45, 41.14, 21.27, 24.01],
        "dividends": [0.6, 1.0, 0.6, 0.6, 0.4]
    },
    "HCA": {
        "prices": [226.14, 217.47, 250.46, 123.94, 133.54],
        "dividends": [0.60 , 0.56, 0.48, 0.43, 0.40]
    },
    "TISCO": {
        "prices": [99.75, 99.25, 89.10, 76.99, 78.06],
        "dividends": [9.75, 7.15, 5.84, 6.74, 5.50]
    },
    "AMZN": {
        "prices": [151.94, 84.00, 166.72, 162.85, 92.39],
        "dividends": [0 , 0, 0, 0, 0]
    },
    "ICHI": {
        "prices": [15.70, 11.30, 10.00, 9.25, 5.05],
        "dividends": [1.10, 0.5, 0.5, 0.35, 0.05]
    },
    "O": {
        "prices": [57.42, 63.43, 71.59, 60.24, 71.35],
        "dividends": [3.059, 2.969, 2.845, 2.801, 2.717]
    }
}

convert to JSON to more analyze in the future (not used in this solution)

In [2]:
import json

years = [2566, 2565, 2564, 2563, 2562]

# Create the JSON structure
stock_data = {"stocks": []}

for ticker, data in stock_info.items():
    stock_entry = {
        "ticker": ticker,
        "historical_data": {
            "prices": [
                {"year": str(year), "close": data["prices"][index]} 
                for index, year in enumerate(years)
            ],
            "dividends": [
                {"year": str(year), "dividend_amount": data["dividends"][index]} 
                for index, year in enumerate(years)
            ],
        }
    }
    stock_data["stocks"].append(stock_entry)

# Output the result as a JSON string (you can write this to a file if needed)
json_output = json.dumps(stock_data, indent=4)

# Optionally, write to a file
with open("../out/stock_data.json", "w") as json_file:
    json_file.write(json_output)

# clean data

In [3]:
import pandas as pd
import numpy as np
import math
import sys
np.set_printoptions(threshold=sys.maxsize, linewidth=1000, precision=3)

years = [2562, 2563, 2564, 2565, 2566]
# Create a new structure for Dividend Yield (%)
dividend_yield_data = {year: {} for year in years}
num_years = len(years) # 5

for ticker, data in stock_info.items():
    for index, year in enumerate(years): 
        price = data["prices"][num_years - 1 - index]  # Access prices in reverse order
        dividend = data["dividends"][num_years - 1 - index]  # Access dividends in reverse order
        dividend_yield = (dividend / price) * 100 if price != 0 else 0
        
        dividend_yield_data[year][ticker] = dividend_yield

# Convert the data into a DataFrame for better visualization
dividend_yield_df = pd.DataFrame(dividend_yield_data).T

# Convert the DataFrame to a NumPy array without the year column
dividend_yield_matrix = dividend_yield_df.to_numpy()

print(dividend_yield_df.to_string())
print("Shape of you",dividend_yield_matrix.shape)

         SAPPE       UNH        VZ        ENB       PTT        UL       KTB      MSFT       SAT      TSMC       SCB       JPM      Visa  META       TOP      BMWG        AP      ABBV       KBS       NVDA  Cpaxt     APPLE       AVGO        LH       SIRI       CVX        ORI       PSEC       KCE       HCA     TISCO  AMZN      ICHI         O
2562  3.316583  1.500102  5.546715  11.800000  4.540598  3.061825  3.829787  0.658710  8.638957  2.924083  4.892368  3.490401  0.621272   0.0  3.082437  4.785343  5.369128  4.833973  3.738318  17.927171    0.0  1.394495  35.443038  6.632653   7.339450  4.883554  10.161871  11.180124  1.665973  0.299536  7.045862   0.0  0.990099  3.807989
2563  4.300518  1.377324  5.432640  13.556485  4.709660  3.186319  6.756757  0.272123  8.196721  1.279742  4.910479  3.824092  1.015658   0.0  0.961538  3.461166  6.206897  4.405040  2.238806  10.865874    0.0  0.687715  30.486412  7.547170   4.938272  7.148795   4.341317  13.308688  2.820874  0.346942  8.754384   0.0 

# Choose 5 stock from 34 to analyze

In [4]:
# Choose 5 stocks from 34 to analyze by permutation
import itertools

stocks = list(stock_info.keys())
combinations = list(itertools.combinations(stocks, 5))

print(f'Total number of combinations : {len(combinations)}')
print(f'First 5 combinations :\n{np.array(combinations[:5])}') 

Total number of combinations : 278256
First 5 combinations :
[['SAPPE' 'UNH' 'VZ' 'ENB' 'PTT']
 ['SAPPE' 'UNH' 'VZ' 'ENB' 'UL']
 ['SAPPE' 'UNH' 'VZ' 'ENB' 'KTB']
 ['SAPPE' 'UNH' 'VZ' 'ENB' 'MSFT']
 ['SAPPE' 'UNH' 'VZ' 'ENB' 'SAT']]


# Covariance matrix & Bordered Hessian matrix

In [5]:
import numpy as np
from joblib import Parallel, delayed
from tqdm import tqdm

def calculate_covariance_matrix(selected_dividend_yield_matrix):
    """Calculate the covariance matrix for the selected stocks."""
    mean_values = np.mean(selected_dividend_yield_matrix, axis=0)
    centered_data = selected_dividend_yield_matrix - mean_values
    covariance_matrix = (centered_data.T @ centered_data) / (selected_dividend_yield_matrix.shape[0] - 1)
    return covariance_matrix, mean_values

def calculate_bordered_hessian(covariance_matrix, mean_values):
    """Calculate the bordered Hessian matrix."""
    n = covariance_matrix.shape[0]
    expected_returns = mean_values
    negative_identity = -np.identity(n)
    combined_matrix = np.hstack((
        covariance_matrix, 
        np.where(negative_identity == -0, 0, negative_identity), 
        np.ones((n, 1)), 
        expected_returns.reshape(-1, 1)
    ))

    vertical_one = np.ones((1, n))
    vertical_zero = np.zeros((1, n+2))
    combined_vertical = np.hstack((vertical_one, vertical_zero))
    combined_matrix = np.vstack((combined_matrix, combined_vertical))

    vertical_expected = expected_returns.reshape(1, -1)
    vertical_zero = np.zeros((1, n+2))
    combined_vertical = np.hstack((vertical_expected, vertical_zero))
    combined_matrix = np.vstack((combined_matrix, combined_vertical))

    return combined_matrix

def process_combination(combination, dividend_yield_matrix, stocks, verbose=True):
    selected_indices = [stocks.index(stock) for stock in combination]
    selected_dividend_yield_matrix = dividend_yield_matrix[:, selected_indices]
    print(f"Selected Dividend:\n{selected_dividend_yield_matrix}") if combination == ('KTB', 'KBS', 'Cpaxt', 'SIRI', 'KCE') and verbose else None

    # Step 1: Calculate the covariance matrix and mean values
    covariance_matrix, mean_values = calculate_covariance_matrix(selected_dividend_yield_matrix)
    print(f"Mean_values:\n{mean_values}") if combination == ('KTB', 'KBS', 'Cpaxt', 'SIRI', 'KCE') and verbose else None
    print(f"Covariance_matrix:\n{covariance_matrix}") if combination == ('KTB', 'KBS', 'Cpaxt', 'SIRI', 'KCE') and verbose else None

    # Step 2: Calculate the H matrix
    bordered_hessian = calculate_bordered_hessian(covariance_matrix, mean_values)
    print(f"Bordered_hessian:\n{bordered_hessian}") if combination == ('KTB', 'KBS', 'Cpaxt', 'SIRI', 'KCE') and verbose else None

    return combination, covariance_matrix, bordered_hessian

In [6]:
H_matrices = {}

# Use joblib for parallel execution with a progress bar
results = Parallel(n_jobs=-1)(
    delayed(process_combination)(combination, dividend_yield_matrix, stocks, verbose=False)
    for combination in tqdm(combinations)
)

# Store the results
for combination, covariance_matrix, bordered_hessian in results:
    H_matrices[combination] = (bordered_hessian,covariance_matrix)

print("All possible combinations have been analyzed!") if len(H_matrices) == math.comb(34, 5) else print("Some combinations are missing!")

100%|██████████| 278256/278256 [00:16<00:00, 17260.86it/s]


All possible combinations have been analyzed!


In [7]:
import pprint
ll = process_combination(('KTB', 'KBS', 'Cpaxt', 'SIRI', 'KCE'), dividend_yield_matrix, stocks)
print(f"{'-' * 100}")
print(f"len of H_matrices : {len(H_matrices)}")
print(f"Structure of H_matrices : ")
pprint.pprint(H_matrices[('KTB', 'KBS', 'Cpaxt', 'SIRI', 'KCE')])

Selected Dividend:
[[ 3.83   3.738  0.     7.339  1.666]
 [ 6.757  2.239  0.     4.938  2.821]
 [ 2.121  0.     0.     4.878  1.458]
 [ 2.373  0.     0.     8.523  1.157]
 [ 3.696  9.091  0.    11.299  1.277]]
Mean_values:
[3.755 3.014 0.    7.396 1.676]
Covariance_matrix:
[[ 3.4    1.614  0.    -1.264  1.133]
 [ 1.614 14.056  0.     7.445 -0.275]
 [ 0.     0.     0.     0.     0.   ]
 [-1.264  7.445  0.     7.223 -1.102]
 [ 1.133 -0.275  0.    -1.102  0.447]]
Bordered_hessian:
[[ 3.4    1.614  0.    -1.264  1.133 -1.     0.     0.     0.     0.     1.     3.755]
 [ 1.614 14.056  0.     7.445 -0.275  0.    -1.     0.     0.     0.     1.     3.014]
 [ 0.     0.     0.     0.     0.     0.     0.    -1.     0.     0.     1.     0.   ]
 [-1.264  7.445  0.     7.223 -1.102  0.     0.     0.    -1.     0.     1.     7.396]
 [ 1.133 -0.275  0.    -1.102  0.447  0.     0.     0.     0.    -1.     1.     1.676]
 [ 1.     1.     1.     1.     1.     0.     0.     0.     0.     0.     0.     0.

# Solve Equation

In [8]:
import itertools
import numpy as np
from joblib import Parallel, delayed
from tqdm import tqdm
# Define a function to compute solutions for a single combination and ci_case
def compute_solutions(combination, covariance_matrix, H, ci_case, r):
    n = H.shape[0] - 2  # Number of stocks (n = 5 in this case)
    cols_to_keep = []

    # Determine which rows/columns to keep based on the current ci_case
    for i, ci in enumerate(ci_case):
        if ci == 1:  # c_i > 0, lambda_i = 0
            cols_to_keep.append(i)  # Keep c_i column
        else:  # c_i = 0, lambda_i > 0
            cols_to_keep.append(i + n)  # Keep lambda_i column
    # Add rows/columns for the additional constraints (1 and E parts)
    cols_to_keep += [H.shape[1]-2, H.shape[1] -1]  # Keep columns for 1 and expected returns (E)
    cols_to_keep.sort() #!! 2 days to solve this bug (forgot to sort) T^T
    
    # Create the reduced matrix H_reduced
    H_reduced = H[:, cols_to_keep]

    # Create the b vector
    b = np.zeros((H.shape[0], 1))
    b[-2] = 1  # Constraint on weights sum
    b[-1] = r  # Required return 'r'
    
    # Try to solve the reduced system
    try:
        if np.linalg.det(H_reduced) > 1e-10: 
            return None
        x_reduced = np.linalg.solve(H_reduced, b)
        return (combination,covariance_matrix, ci_case, x_reduced, H, H_reduced, b)  if np.allclose(H_reduced @ x_reduced, b) else None
    except np.linalg.LinAlgError:
        return None  # Return None if there is an error

In [9]:
import pickle
import os
def save_results(filename, data):
    with open(filename, 'wb') as f:
        pickle.dump(data, f)

def load_results(filename):
    with open(filename, 'rb') as f:
        return pickle.load(f)
    
solutions_file = '../out/raw_data/valid_solutions10Percent.pkl'
r = 10  # Required return of 10%
valid_solutions = {}
# Check if results file exists
if os.path.exists(solutions_file):
    print(f"Loading results from {solutions_file}...")
    valid_solutions = load_results(solutions_file)
else:
    print("Running the computation...")
    combinations_ci = list(itertools.product([0, 1], repeat=5))
    tasks = list(itertools.product(combinations_ci, H_matrices.items()))

    # Parallel computation of results
    results = Parallel(n_jobs=-1)(
        delayed(compute_solutions)(
            combination,
            covariance_matrix,
            H,
            ci_case,
            r
        )
        for ci_case, (combination, (H, covariance_matrix)) in tqdm(tasks, desc="Processing tasks", total=len(tasks))
    )
    # Filter out None results and organize them into the solutions dictionary
    print("Filtering out None results...")
    solutions = {}
    for result in results:
        if result:
            combination, covariance_matrix, ci_case, x_reduced, H, H_reduced, b = result
            if combination not in solutions:
                solutions[combination] = []  # Initialize an empty list for this combination
            solutions[combination].append((covariance_matrix, ci_case, x_reduced, H, H_reduced, b))
    print("Successfully filtered out None results!")
    
    # Filter to get only valid solutions (lampda>=0, c>=0)
    print("Filtering valid solutions... (lampda>=0, c>=0)")
    for combination, solution_list in solutions.items():
        for covariance_matrix, ci_case, x_reduced, H, H_reduced, b in solution_list:
            checker = {}
            x_values = x_reduced.flatten()  # Convert the array to a 1D array
            mu_values = {}
            mu_values['mu1'] = x_values[-1]
            mu_values['mu2'] = x_values[-2]
            increment = 0
            for i,case in enumerate(ci_case):
                if case == 1:
                    checker[f'c{i+1}'] = x_values[increment]
                    increment += 1
            for i,case in enumerate(ci_case):
                if case == 0:
                    checker[f'lambda{i+1}'] = x_values[increment]
                    increment += 1

            if all(value>=0 for value in checker.values()):
                if combination not in valid_solutions:
                    valid_solutions[combination] = []
                valid_solutions[combination].append((covariance_matrix, ci_case, x_reduced, checker, mu_values))
    print(f"Total number of valid solutions: {len(valid_solutions)}")
    print(f"Saving valid solutions to {solutions_file}...")
    save_results(solutions_file, valid_solutions)
    print(f"Successfully saved valid solutions!")

Running the computation...


Processing tasks: 100%|██████████| 8904192/8904192 [16:44<00:00, 8868.04it/s] 


Filtering out None results...
Successfully filtered out None results!
Filtering valid solutions... (lampda>=0, c>=0)
Total number of valid solutions: 52856
Saving valid solutions to ../out/raw_data/valid_solutions10Percent.pkl...
Successfully saved valid solutions!


In [10]:
# print(f"Total number of solutions: {len(solutions)}")
# tester = solutions[('KTB', 'KBS', 'Cpaxt', 'SIRI', 'KCE')][0]
# print(f"covariance_matrix:\n{pd.DataFrame(tester[0]).to_string()}");print(f"{'-' * 100}")
# print(f"ci_case:\n{pd.DataFrame(tester[1]).to_string()}");print(f"{'-' * 100}")
# print(f"x_reduced:\n{pd.DataFrame(tester[2]).to_string()}");print(f"{'-' * 100}")
# print(f"H:\n{pd.DataFrame(tester[3]).to_string()}");print(f"{'-' * 100}")
# print(f"H_reduced:\n{pd.DataFrame(tester[4]).to_string()}");print(f"{'-' * 100}")
# print(f"b:\n{pd.DataFrame(tester[5]).to_string()}");print(f"{'-' * 100}")
# # print the first solution for debugging
# for combination, solution_list in solutions.items():
#     if combination == ('KTB', 'KBS', 'Cpaxt', 'SIRI', 'KCE'):
#         print(f"Combination : {combination}")
#         print(f"Number of solutions : {len(solution_list)}")
#         print(f"First solution : {solution_list[0]}")
#         break

# Manage portfolio

# Add risk

In [11]:
valid_solutions_with_risk = {}
for combination, solution_list in valid_solutions.items():
    for covariance_matrix, ci_case, x_reduced, checker, mu_values in solution_list:
        myPort = {}
        for key in ['c1', 'c2', 'c3', 'c4', 'c5']:
            if key in checker:
                myPort[key] = checker[key]  # Append c_i and its value
            else:
                myPort[key] = 0  # Set value to 0 for other indices
        # convert myPort to numpy array
        myPort = np.array([myPort['c1'], myPort['c2'], myPort['c3'], myPort['c4'], myPort['c5']]).reshape(-1, 1)
        risk = np.sqrt(myPort.T @ covariance_matrix @ myPort)
        
        if combination not in valid_solutions_with_risk:
            valid_solutions_with_risk[combination] = []
        valid_solutions_with_risk[combination].append((myPort, risk.item(),(covariance_matrix, ci_case, x_reduced, checker, mu_values)))

In [12]:
for combination, solution_list in valid_solutions_with_risk.items():
    print(f"Combination : {combination}")
    print(f"Number of valid solutions :\n{solution_list}")
    for _,_,i in solution_list:
        print(pd.DataFrame(i[0]).to_string())
        print(pd.DataFrame(i[1]).to_string())
        print(pd.DataFrame(i[2]).to_string())
        print(pd.DataFrame(i[3], index=[0]).to_string())
        print(pd.DataFrame(i[4], index=[0]).to_string())
    break
            

Combination : ('SAPPE', 'UNH', 'VZ', 'ENB', 'PTT')
Number of valid solutions :
[(array([[0.   ],
       [0.   ],
       [0.255],
       [0.745],
       [0.   ]]), 0.9868156601524832, (array([[ 0.968, -0.015, -0.907,  1.068, -0.44 ],
       [-0.015,  0.024,  0.012,  0.112,  0.053],
       [-0.907,  0.012,  1.028, -0.796,  0.212],
       [ 1.068,  0.112, -0.796,  2.18 , -0.296],
       [-0.44 ,  0.053,  0.212, -0.296,  1.494]]), (0, 0, 1, 1, 0), array([[ 0.255],
       [ 0.745],
       [ 1.907],
       [ 2.062],
       [ 0.755],
       [ 2.423],
       [-0.34 ]]), {'c3': 0.2551587621331539, 'c4': 0.7448412378668459, 'lambda1': 1.9069013496176577, 'lambda2': 2.0621780206635734, 'lambda5': 0.7552694721008626}, {'mu1': -0.33964798405382, 'mu2': 2.4226746934160195}))]
          0         1         2         3         4
0  0.968318 -0.014918 -0.906962  1.067971 -0.440070
1 -0.014918  0.023633  0.011845  0.112457  0.052812
2 -0.906962  0.011845  1.028219 -0.795885  0.211839
3  1.067971  0.1124

In [13]:
import pandas as pd
import numpy as np

# Assuming valid_solutions is already defined
data = []  # List to store the rows for the DataFrame

for combination, solution_list in valid_solutions.items():
    for covariance_matrix, ci_case, x_reduced, checker, mu_values in solution_list:
        myPort = {}
        for key in ['c1', 'c2', 'c3', 'c4', 'c5']:
            myPort[key] = checker.get(key, 0)  # Set value to 0 if key is not in checker
            
        # Convert myPort to numpy array
        myPort_array = np.array([myPort['c1'], myPort['c2'], myPort['c3'], myPort['c4'], myPort['c5']]).reshape(-1, 1)
        risk = np.sqrt(myPort_array.T @ covariance_matrix @ myPort_array)
        
        # Append the combination, myPort, and risk.item() to the data list
        data.append((combination, myPort_array.flatten(), risk.item(),covariance_matrix,ci_case,x_reduced,checker,mu_values))  # Flatten myPort for better representation

# Create a DataFrame
df_valid_solutions = pd.DataFrame(data, columns=['Combination', 'myPort', 'Risk', 'Covariance Matrix', 'ci_case', 'x_reduced', 'checker', 'mu_values'])

# Display the DataFrame
print(df_valid_solutions)


                          Combination  \
0          (SAPPE, UNH, VZ, ENB, PTT)   
1           (SAPPE, UNH, VZ, ENB, UL)   
2          (SAPPE, UNH, VZ, ENB, KTB)   
3         (SAPPE, UNH, VZ, ENB, MSFT)   
4          (SAPPE, UNH, VZ, ENB, SAT)   
...                               ...   
52931   (ENB, SAT, META, Cpaxt, AMZN)   
52932  (ENB, TSMC, META, Cpaxt, AMZN)   
52933   (ENB, SCB, META, Cpaxt, AMZN)   
52934   (ENB, JPM, META, Cpaxt, AMZN)   
52935  (ENB, Visa, META, Cpaxt, AMZN)   

                                                  myPort      Risk  \
0      [0.0, 0.0, 0.2551587621331539, 0.7448412378668...  0.986816   
1      [0.0, 0.0, 0.2551587621331539, 0.7448412378668...  0.986816   
2      [0.0, 0.0, 0.2551587621331539, 0.7448412378668...  0.986816   
3      [0.0, 0.0, 0.2551587621331539, 0.7448412378668...  0.986816   
4      [0.0, 0.0, 0.2551587621331539, 0.7448412378668...  0.986816   
...                                                  ...       ...   
52931  [0.8521801

In [14]:
df_valid_solutions.to_csv('../out/Solutions10percent.csv', index=False)